package com.toolbox.admin.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors (neumorphism: soft light-gray base #E8ECF3 — matches app theme)
val LightPrimary = Color(0xFF6C63FF)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE3E1FF)
val LightOnPrimaryContainer = Color(0xFF1B1464)
val LightSecondary = Color(0xFF5A6079)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDEE3F0)
val LightOnSecondaryContainer = Color(0xFF181C2B)
val LightBackground = Color(0xFFE8ECF3)
val LightOnBackground = Color(0xFF1C1F26)
val LightSurface = Color(0xFFF1F4FA)
val LightOnSurface = Color(0xFF1C1F26)
val LightSurfaceVariant = Color(0xFFDDE2EC)
val LightOnSurfaceVariant = Color(0xFF454A57)
val LightOutline = Color(0xFF868CA0)
val LightOutlineVariant = Color(0xFFC7CCDA)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFF9DEDC)
val LightOnErrorContainer = Color(0xFF410E0B)

// Dark Theme Colors
val DarkPrimary = Color(0xFFD0BCFF)
val DarkOnPrimary = Color(0xFF371E73)
val DarkPrimaryContainer = Color(0xFF4F378B)
val DarkOnPrimaryContainer = Color(0xFFEADDFF)
val DarkSecondary = Color(0xFFCCC2DC)
val DarkOnSecondary = Color(0xFF332D41)
val DarkSecondaryContainer = Color(0xFF4A4458)
val DarkOnSecondaryContainer = Color(0xFFE8DEF8)
val DarkBackground = Color(0xFF1C1B1F)
val DarkOnBackground = Color(0xFFE6E1E5)
val DarkSurface = Color(0xFF242329)
val DarkOnSurface = Color(0xFFE6E1E5)
val DarkSurfaceVariant = Color(0xFF49454F)
val DarkOnSurfaceVariant = Color(0xFFCAC4D0)
val DarkOutline = Color(0xFF938F99)
val DarkOutlineVariant = Color(0xFF49454F)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)
val DarkErrorContainer = Color(0xFF8C1D18)
val DarkOnErrorContainer = Color(0xFFF9DEDC)
